apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-utils
  labels:
    app: kube-utils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-utils
  template:
    metadata:
      labels:
        app: kube-utils
    spec:
      containers:
      - image: joway/dockerize-utils:24a6ae9
        name: kube-utils
